### ISSUE TITLE
Print to file output formats

### ISSUE THREAD

**Issue by rfuest** [gtkwave/gtkwave#101]
I'm still working on slowly refactoring the waveform display and I'm currently fixing functions that were temporarily broken during the rewrite. One of the biggest remaining TODO items is `print.c`, which was affected by changes in `GLOBALS`.

There are two ways I could fix this file. One would be to adapt the existing code to the new `GLOBALS` and the other would be to change the print support to always use cairo for drawing. I prefer the second option, because it would be possible to remove a lot of code duplication and make the code easier to maintain/extend in the future. The code in `print.c` is already slightly out of sync with the widget drawing code and e.g. doesn't use the special drawing style for zero and one vectors.

One regression of always using cairo is that it would no longer be possible to export MIF files. I haven't used FrameMaker myself and cannot judge if this is a problem. But we would gain support for exporting SVG files and PDF export without using `ps2pdf`.

**Comment by gtkwave** [comment]
Cairo sounds like the way to go.

MIF files at this point are pretty obsolete, as far as I'm concerned.  I haven't had to use them on the job for almost 10 years.
-Tony


    On Monday, December 6, 2021, 11:42:40 AM EST, Ralf Fuest ***@***.***> wrote:  
 
 


I'm still working on slowly refactoring the waveform display and I'm currently fixing functions that were temporarily broken during the rewrite. One of the biggest remaining TODO items is print.c, which was affected by changes in GLOBALS.

There are two ways I could fix this file. One would be to adapt the existing code to the new GLOBALS and the other would be to change the print support to always use cairo for drawing. I prefer the second option, because it would be possible to remove a lot of code duplication and make the code easier to maintain/extend in the future. The code in print.c is already slightly out of sync with the widget drawing code and e.g. doesn't use the special drawing style for zero and one vectors.

One regression of always using cairo is that it would no longer be possible to export MIF files. I haven't used FrameMaker myself and cannot judge if this is a problem. But we would gain support for exporting SVG files and PDF export without using ps2pdf.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
