### ISSUE TITLE
[+] and [-] in populateBuffer

### ISSUE THREAD

**Issue by rfuest** [gtkwave/gtkwave#103]
`populateBuffer` contains some code to handle `[+]` and `[-]` prefixes but I couldn't find any instances where traces with these prefixes are created. Is this feature still used?

**Comment by gtkwave** [comment]
I believe it's for BlueSpec-specific usage:
GitHub - B-Lang-org/bdw: BSC Development Workstation (BDW)
./testing/bsc.bdw/commands/1v.NovasRC.typed.dump.expected:userCompositeMem /main/top/iv/data3 [0] [1] [+] [Vector#(2, Bool)]./testing/bsc.bdw/commands/1v.NovasRC.typed.dump.expected:userCompositeMem /main/top/iv/data3 [0] [0] [+] [Vector#(2, Bool)]

-Tony


    On Tuesday, December 7, 2021, 12:50:48 PM EST, Ralf Fuest ***@***.***> wrote:  
 
 


populateBuffer contains some code to handle [+] and [-] prefixes but I couldn't find any instances where traces with these prefixes are created. Is this feature still used?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rfuest** [comment]
Thanks for the link. So this is just a visual indicator that these traces can be expanded and requires an alias in the savefile: https://github.com/B-Lang-org/bdw/blob/main/testing/bsc.bdw/commands/1v.GtkWaveScript.bits.dump.expected#L863-L869
I'll add it to my growing list of tests.
