### ISSUE TITLE
RFE: Method for an external process to move the cursor/add marker/run TCL commands on an already running GTKWave process

### ISSUE THREAD

**Issue by tomverbeure** [gtkwave/gtkwave#109]
I have a work-in-progress tool that reads in an FST file, extracts the program counter and memory transactions, and then acts as a gdb server. This allows me to debug a simulated CPU with GDB after the fact: set breakpoints, inspect memory locations etc.

What I'd like to add is to link the gdb server to GTKWave, so that the server can move the waveform viewer to the time location where, say, a breakpoint was triggered. In practice, I think this means that GTKWave would have to create a server socket through which it can accept TCL commands.

Is there already some kind of mechanism in GTKWave that would allow me to do something like this?

Thanks!
Tom

**Comment by gtkwave** [comment]
There's no explicit mechanism to have a server socket accept Tcl commands.  I would suppose it's possible with a Tcl script running that listened to a socket and sent what was sent to it through something like "eval" or whatever.  I don't know if it would require usage of the repscript (-R/-P) functionality.  My guess is it might.

-Tony

    On Sunday, December 26, 2021, 08:20:02 PM EST, Tom Verbeure ***@***.***> wrote:  
 
 


I have a work-in-progress tool that reads in an FST file, extracts the program counter and memory transactions, and then acts as a gdb server. This allows me to debug a simulated CPU with GDB after the fact: set breakpoints, inspect memory locations etc.

What I'd like to add is to link the gdb server to GTKWave, so that the server can move the waveform viewer to the time location where, say, a breakpoint was triggered. In practice, I think this means that GTKWave would have to create a server socket through which it can accept TCL commands.

Is there already some kind of mechanism in GTKWave that would allow me to do something like this?

Thanks!
Tom

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tomverbeure** [comment]
I wasn't aware of the existence of the repscript option. It'd obviously be a dirty hack, but it might just be the way to get to where I want.

Thanks!
Tom
