### ISSUE TITLE
Converting from VCD to AET file

### ISSUE THREAD

**Issue by chrisbaldwin2** [gtkwave/gtkwave#121]
Hi there. Is there a way to convert a VCD dump to an AET file?

**Comment by gtkwave** [comment]
Chris,
I have no idea what passes for an AET file since Sustik left or what versions the tools support.  If you want, send me a private mail and cc: Steve Bergman (I think his alias is "wiseguy") on it provided he's still around.

-Tony

    On Monday, April 25, 2022, 01:48:09 PM EDT, chrisbaldwin2 ***@***.***> wrote:  
 
 


Hi there. Is there a way to convert a VCD dump to an AET file?

**Comment by chrisbaldwin2** [comment]
Thanks for the quick response. I'm not sure what your email is and I don't see Steve on github or the contributors. Do you mind starting the thread with my email cgb2@illinois.edu
