### ISSUE TITLE
export only selected or visible signals

### ISSUE THREAD

**Issue by jotego** [gtkwave/gtkwave#175]
The current export feature (in version 3.3.103) exports the whole database. This is akin to a conversion tool to go from one format to another. It would be more useful if you could export only a subset of the database. 

Cadence Simvision allows you to export only the selected signals. Either the selected ones or those visible in the scope will be fine. Exporting a subset of the signals is useful to perform analysis using other tools or to share simulation data with other developers.

**Comment by gtkwave** [comment]
I believe that it only exports what signals are available onscreen (including scrolling up/down) or are used for the solid blue and dashed blue marker generation.  This is in order to make a more manageable subset of viewable scope state, for example, from a large FSDB or FST file.

-Tony

    On Saturday, December 3, 2022, 05:22:36 AM EST, JOTEGO ***@***.***> wrote:  
 
 


The current export feature (in version 3.3.103) exports the whole database. This is akin to a conversion tool to go from one format to another. It would be more useful if you could export only a subset of the database.

Cadence Simvision allows you to export only the selected signals. Either the selected ones or those visible in the scope will be fine. Exporting a subset of the signals is useful to perform analysis using other tools or to share simulation data with other developers.

**Comment by jotego** [comment]
Indeed, that's the workaround I have been using during 2023. It is not ideal, but it is good enough. I will close the issue. Thanks.
