### ISSUE TITLE
Bug in text box for pattern search

### ISSUE THREAD

**Issue by shareefj** [gtkwave/gtkwave#197]
Hi,

there's an annoying bug in the text box within the pattern search window.  If you enter a value and then go back to edit it, deleting any character then seems to auto highlight the whole string which is overwritten with further typing.  So to modify a string you first have to delete a single character at a time followed by pressing the right arrow key to un-highlight the string.  PITA.

This is on 3.3.104 and 3.3.115 which is all I've tested.

Shareef.

**Comment by gtkwave** [comment]
The annoying bug is because most people won't press enter to update search results before pressing one of the buttons, so the question is how to get the current string data reported by the widget.  I don't know if it would require a custom widget or a different method to update the current string data for searches.

-Tony

    On Tuesday, April 11, 2023 at 09:25:44 AM EDT, shareefj ***@***.***> wrote:  
 
 


Hi,

there's an annoying bug in the text box within the pattern search window. If you enter a value and then go back to edit it, deleting any character then seems to auto highlight the whole string which is overwritten with further typing. So to modify a string you first have to delete a single character at a time followed by pressing the right arrow key to un-highlight the string. PITA.

This is on 3.3.104 and 3.3.115 which is all I've tested.

Shareef.

**Comment by shareefj** [comment]
OK, so just for my understanding, you have a callback that fakes an enter key press because the new value needs to be updated before any button is pressed?

And will the suggested fix by @rfuest be made?

**Comment by gtkwave** [comment]
Sure, totally, include the change.
-Tony

    On Thursday, April 13, 2023 at 10:28:57 AM EDT, Ralf Fuest ***@***.***> wrote:  
 
 



I don't see why it should be changing the selection. It might've been a holdover from the GTK 1.2 days that's no longer required.


I did some quick research using the gtkwave-archive repo (primarily to test the usefulness of the archive). You are correct that this code is very old and did exist at the beginning of the CVS repo. In this commit from 2007 the enter_callback was then also connected to the changed signal: ***@***.***#diff-b3dbb9647cce4420b8d5073ed1c402c93be4d3001bc966dc47dc712ab88fe38d

In the past there was probably a good reason to change the selection on pressing enter, but the selection shouldn't have been modified on all changes to the text. For modern code I would suggest to keep manual changes to the selection to a minimum and to rely on the default behavior of the toolkit.


And will the suggested fix by @rfuest be made?


I can prepare a PR for this change if @gtkwave likes to include this change.
