### ISSUE TITLE
Cursors do not show properly on Wayland

### ISSUE THREAD

**Issue by OpusElectronics** [gtkwave/gtkwave#207]
Probably a well-known issue and rather with GTK than with gtkwave itself, but currently cursors do not show properly when running on Wayland (KDE plasma on Wayland in my case.)

I tested using the same KDE plasma install but with a X11 session instead, and cursors work fine in this case.

Again, probably a well known issue? Hopefully those Wayland hiccups can get ironed out as Wayland is definitely becoming more common on the desktop.

**Comment by OpusElectronics** [comment]
As a follow-up, this "fixes" the issue: https://github.com/gtkwave/gtkwave/issues/173#issuecomment-1332761415
So it'll do for now!

**Comment by rfuest** [comment]
I was able to reproduce your issue. IMO the best idea is to stick with the X11 backend at the moment. It is probably possible to fix this issue by adding more manual redraw calls, but in my experience using GTKWave with Wayland has always be flaky. But I'm also stuck with an old Nvidia graphics card at the moment, which doesn't have the best Wayland support anyway.

A proper fix for Wayland will need bigger changes to the drawing code, which uses the GTK API in unusual ways. The drawing code is still very similar to the GTK 1/2 era code and not like code that has been written from the ground up with GTK 3 in mind. In X11 GTK 3 is close enough to the older version that the code works, but the Wayland backend behaves differently enough for things to break.

I've actually already done a lot of work to refactor the code to modernize it and it did work a lot better under Wayland, but I decided to postpone merging this code and will add it as part of the GTK 4 port. GTK 4 has a completely different drawing model to GTK 3 and targeting GTK 4 will be to most future prove target.

**Comment by OpusElectronics** [comment]
No problem, focusing on GTK4 rather than wasting time on GTK3 does indeed make sense. We have a workaround in the meantime.

I have an AMD GPU, so this problem is not specific to NVidia cards.

**Comment by rfuest** [comment]
> Inserting extra draw_marker() calls one by one until the problem disappears likely would fix this.  I'm sure it's some race condition where there's probably some kind of timing issue involving gdk_window_end_draw_frame() vs draw_marker() or whatever, and (newer versions of) Wayland exposes this.

I did briefly try to fix the issue yesterday and it kind of worked after inserting another `gtk_widget_queue_draw`, but then the baseline marker no longer worked correctly. At that point I decided to not spend any more time on this.

My refactored code still works similar and also uses the backing store to cache the waveform and bsearching to skip to the next pixel. But all drawing code is now inside the `draw` signal handler or methods called by it. Currently some of the drawing is handled by other functions, like `service_hslider`, which makes the code harder to understand and to debug. I've also reduced the need for manual widget updates in the entire codebase by relying on GObject features like signals and property bindings.

**Comment by gtkwave** [comment]
Sounds good with the refactoring.  The manual widget updates were a bit of a hack where widget updates were forced based on a direct user action rather than, for example, the widget pulling current data into it.  Three major toolkit revs, and countless bug updates later, it all winds up similar to Abbott and Costello's "Who's on First" comedy sketch.

https://www.youtube.com/watch?v=sYOUFGfK4bU
-Tony

    On Wednesday, June 7, 2023 at 02:21:15 PM EDT, Ralf Fuest ***@***.***> wrote:  
 
 



Inserting extra draw_marker() calls one by one until the problem disappears likely would fix this. I'm sure it's some race condition where there's probably some kind of timing issue involving gdk_window_end_draw_frame() vs draw_marker() or whatever, and (newer versions of) Wayland exposes this.


I did briefly try to fix the issue yesterday and it kind of worked after inserting another gtk_widget_queue_draw, but then the baseline marker no longer worked correctly. At that point I decided to not spend any more time on this.

My refactored code still works similar and also uses the backing store to cache the waveform and bsearching to skip to the next pixel. But all drawing code is now inside the draw signal handler or methods called by it. Currently some of the drawing is handled by other functions, like service_hslider, which makes the code harder to understand and to debug. I've also reduced the need for manual widget updates in the entire codebase by relying on GObject features like signals and property bindings.

**Comment by rfuest** [comment]
The cursors are now properly updated with Wayland in the master version. Moving the baseline cursor is now smoother than in 3.3.116 with the X11 backend. I think moving the baseline cursor was causing unnecessary redraws of the backing image.
