### ISSUE TITLE
Build fails due to Werror=missing-include-dirs in meson.build

### ISSUE THREAD

**Issue by MrHighVoltage** [gtkwave/gtkwave#289]
Hey GTKWave Team,

I'm currently updating GTKWave to the new Meson build system in our [IIC-OSIC-Tools Docker container](https://github.com/iic-jku/iic-osic-tools). Building GTKWave was impossible due to the following line in the Meson configuration:

[meson.build Line 136: '-Werror=missing-include-dirs',](https://github.com/gtkwave/gtkwave/blob/151148ca26640b54bda951c18e84385c1c0d7423/meson.build#L163C36-L163C36)

The build fails because there is a missing include directory, which is then considered as an error. Removing this line allows to build GTKWave. You still get a Warning because of -Wmissing-include-dirs on Line 182. Unfortunately, I can not tell which include directory is missing, as the compiler is only reporting the error, not the directory.

As the build is successful even with the missing directory, I suggest removing this Werror as it is too exaggerated.

Thank you and best regards,
Georg

**Comment by rfuest** [comment]
I would prefer to find the root cause of this problem instead of just changing the error to a warning. Under normal circumstances the build system should never call the compiler with invalid include directories.

I wasn't able to reproduce the issue with a new Ubuntu 22.04 container. GCC should output the missing directory as part of the error message. If the error message doesn't contain a directory there might be an empty string in the list of include directories, which wouldn't be visible in the error message:
![grafik](https://github.com/gtkwave/gtkwave/assets/226123/a1ce3f33-abbf-41d7-b3b7-7353bcbaa03c)
Please run `meson compile -v` or check the `compile_commands.json` in the build directory to see if there is an empty include directory in the compiler calls.

**Comment by MrHighVoltage** [comment]
Ah I see, I completely overlooked that, because it is "-Iinclude". I just checked the build process and there is no include directory in the build directory after "meson setup build".

On a quick check, I could not find, where this include is defined or when it should be created.

**Comment by rfuest** [comment]
Can you upload the `meson-logs/meson-log.txt` and `compile_commands.json` files from the build directory?

**Comment by MrHighVoltage** [comment]
Files attached!
[meson-log.txt](https://github.com/gtkwave/gtkwave/files/13498592/meson-log.txt)
[compile_commands.json](https://github.com/gtkwave/gtkwave/files/13498593/compile_commands.json)
