### ISSUE TITLE
How to hide leading zeros on the waveform?

### ISSUE THREAD

**Issue by phillbush** [gtkwave/gtkwave#32]
I have the following waveform.  
pc is a 64-bit bus, but only the least significant bits of it are set, the leading bits are zero.

How can I view the value on the waveform without the leading zeros, so they can appear on the screen with the current zoom?  
Or, otherwise, can I make the value align to the right, so that the `+` appears on the left hiding some of the leading zeros?

![scrot_2020-10-29-005716](https://user-images.githubusercontent.com/63266536/97523830-1782b780-199b-11eb-83b9-d78d6480ad21.png)

**Comment by gtkwave** [comment]
Currently there's no way to do it directly. For now, you can compile this and attach it as a process filter.

#include <stdio.h>
int main(int argc, char **argv)
{
while(!feof(stdin))
{
char buf[1025];
buf[0] = 0;
fscanf(stdin, "%s", buf);
if(buf[0])
{
char *buf2 = buf;
while((*buf2=='0') && *(buf2+1)) buf2++;
printf("%s\n", buf2);
fflush(stdout);
}
}
return(0);
}

See "Alias Files and Attaching External Disassemblers" in the documentation gtkwave.pdf (or the .odt file in the tarball).

-Tony


     On Thursday, October 29, 2020, 12:03:23 AM EDT, phillbush <notifications@github.com> wrote:  
 
 


I have the following waveform.
pc is a 64-bit bus, but only the least significant bits of it are set, the leading bits are zero.

How can I view the value on the waveform without the leading zeros, so they can appear on the screen with the current zoom?
Or, otherwise, can I make the value align to the right, so that the + appears on the left hiding some of the leading zeros?

**Comment by MrJake222** [comment]
As it is highest result of google search `gtkwave leading zeros`, I feel obliged to post this:

![lz](https://github.com/gtkwave/gtkwave/assets/7581790/2e7f3d38-7af9-4ded-810b-98258a2cc2d3)

**Comment by KireinaHoro** [comment]
@MrJake222 which version of GTKWave are you using?  I don't see such an option in v3.3.104...

**Comment by tbybell** [comment]
3.3.108 or greater.

**Comment by KireinaHoro** [comment]
Thanks!Am 22.08.2024 um 18:15 schrieb tbybell ***@***.***>:﻿
3.3.108 or greater.
