### ISSUE TITLE
Properly handle filter process crashes

### ISSUE THREAD

**Issue by FurryAcetylCoA** [gtkwave/gtkwave#334]
Hello everyone.

I noticed that gtkwave freeze if a filter process executable is incompatible with the target system (e.g., due to a missing shared library)

When such executable is added, the **second** child process forked in `pipeio_create` crashes immediately after `execl`. This crash leaves the "other end" of the pipes open, which are held by the **first** child process, causing the system to incorrectly assume the pipes are still valid. Consequently, when the pipes are accessed later, such as in `pdofilter` in `baseconvert.c`, the application hangs because `fgets` on line 128 never returns.

I've already wrote a [patch](https://github.com/gtkwave/gtkwave/commit/862b21c329ae59f9dbf181145e13417ecf69045b) that ensures the pipe closes as expected when the filter process crashes, preventing `fgets` from blocking gtkwave.

Additionally, I've drafted another patch to clean up and remove the faulty filter from the list ( and possibly generate a warning ) when a crash is detected:
```diff
--- a/src/baseconvert.c	
+++ b/src/baseconvert.c	
 if (n) {
             if (buf[n - 1] == '\n') {
                 buf[n - 1] = 0;
                 n--;
             }
        }
+#if !defined __MINGW32__
+        else {
+            if(waitpid(p->pid, NULL, WNOHANG) == p->pid) { /* filter died */
+                // Close the pipes. 
+                //  Then clean-up.?
+            }
+        }
+#endif
 
         if (buf[0]) {
             free_2(s);
```

### Question

I'm considering how to handle the removal of a crashed filter process without leaving gaps in the GLOBALS->proc_filter array (or just ignore it? but the SIGPIPE can be annoying for developers)

I would appreciate any suggestions on how to more elegantly handle and cleanup after a filter process crash in `baseconvert.c`.

 Thank you for your attention and any suggestions you might have!

**Comment by rfuest** [comment]
I have planned to replace the process filter code with a new implementation that uses Gio's `GSubprocess` instead of the POSIX API. The new code uses a `GwProcessFilter` object to manage the process filter, this object will continue to exist even after the subprocess has crashed.

You can take a look at my work in progress code here: https://github.com/rfuest/gtkwave/commit/0650039f916271f1f112225f1ca35e630ae69dd1 It isn't integrated into the rest of GTKWave yet, but the unit test should give you an idea how it works. In the final implementation there should be some feedback to the user that the filter process has crashed.
