### ISSUE TITLE
fsdb2vcd

### ISSUE THREAD

**Issue by michael-etzkorn** [gtkwave/gtkwave#85]
I noticed some code that converts fsdb2vcd https://github.com/gtkwave/gtkwave/blob/master/gtkwave3/contrib/fsdb2vcd/fsdb2vcd_fast.cc is there a way to invoke this from the CLI?

**Comment by umarcor** [comment]
It's a CLI tool itself. On MSYS2:

```
# which fst2vcd
/mingw64/bin/fst2vcd

# fst2vcd --help
C:\msys64\mingw64\bin\fst2vcd.exe: unknown option -- -
Usage: C:\msys64\mingw64\bin\fst2vcd.exe [OPTION]... [FSTFILE]

  -f                         specify FST input filename
  -o                         specify output filename
  -e                         emit FST extensions to VCD
  -h                         display this help then exit

VCD is emitted to stdout if output filename is unspecified.

Report bugs to <bybell@rocketmail.com>.
```

**Comment by gtkwave** [comment]
67:/tool/verdi/2020.03-SP2-6> find . | grep libnsys.so./share/FsdbReader/linux/libnsys.so
./share/FsdbReader/linux64/libnsys.so
./share/FsdbReader/linux64_gcc620/libnsys.so
./share/FsdbReader/linux_gcc620/libnsys.so
./share/FsdbReader_pure/linux/libnsys.so
./share/FsdbReader_pure/linux64/libnsys.so
./share/libcmd/linux/libnsys.so
./share/libcmd/linux64/libnsys.so
./share/libcmd/linux64_gcc620/libnsys.so
./share/libcmd/linux_gcc620/libnsys.so
./share/novas_dnd/linux/libnsys.so
./share/novas_dnd/linux64/libnsys.so
./share/novas_dnd/linux64_gcc620/libnsys.so
./share/novas_dnd/linux_gcc620/libnsys.so
./share/vcst/linux/libnsys.so
./share/vcst/linux64/libnsys.so

...it may be in a different place on your system.  Also look under vcs:
70:/tool/vcs/2020.03-SP2-6> find . | grep libnsys.so
./vcfca/linux/vcst/lib/libnsys.so
./vcfca/linux64/vcst/lib/libnsys.so

-Tony


    On Monday, October 18, 2021, 9:59:35 AM EDT, Michael Etzkorn 明凯 ***@***.***> wrote:  
 
 


Unfortunately, I haven't been able to find the one bundled with Verdi, nor can I find reference to these libraries, but I'll see if I can find a solution. Appreciate the response!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by michael-etzkorn** [comment]
I managed to find it! I also found fsdb2vcd from Verdi. Thanks for the help :D
