### ISSUE TITLE
Feature: filter on all port direction types

### ISSUE THREAD

**Issue by tomverbeure** [gtkwave/gtkwave#92]
Right now, you can use +I+, +O+, +IO+ to retain input, output, and inout port.

However, I don't see a way retain all ports, regardless of direction?

E.g. something like this: +*+ or +A+ (all)

Tom

**Comment by gtkwave** [comment]
Try using something like minus minus instead of plus.
-Tony

    On Wednesday, November 3, 2021, 01:57:28 PM EDT, Tom Verbeure ***@***.***> wrote:  
 
 


Right now, you can use +I+, +O+, +IO+ to retain input, output, and inout port.

However, I don't see a way retain all ports, regardless of direction?

E.g. something like this: +*+ or +A+ (all)

Tom

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tomverbeure** [comment]
Manual was updated with commit 13fc69b24caa203d3b1946eb228d462c1e9d98c5. Closing.
