### ISSUE TITLE
BitsToReal not working for 32-bit signal

### ISSUE THREAD

**Issue by YingXiangLi10** [gtkwave/gtkwave#98]
BitsToReal seems to work fine for 32-bit signal according to the help text.

I have a 32-bit reg type signal, when i select "BitsToReal" option in data format, it only shows the binary of the signal.

**Comment by gtkwave** [comment]
What version, OS, etc?  I just tried it and it seemed to work for me.  Also, if you have a VCD you can share, that would help too.
-Tony

    On Saturday, November 13, 2021, 12:04:11 AM EST, YingXiangLi10 ***@***.***> wrote:  
 
 


BitsToReal seems to work fine for 32-bit signal according to the help text.

I have a 32-bit reg type signal, when i select "BitsToReal" option in data format, it only shows the binary of the signal.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YingXiangLi10** [comment]
Sorry for not replying for a long time.

**Comment by YingXiangLi10** [comment]
Sorry for not replying for so long. The problem is solved when I use the latest version. The problem was happened in the version 3 years ago, back to  3.3.9x, which can be install with apt-get. 

Thanks for this wonderful wave viewer, it's fast and super helpful.
